rvm:
  - 1.8.6
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - rbx-18mode
  - rbx-19mode
  - jruby-18mode
  - jruby-19mode
  - ruby-head
env:
  - "rack=1.1.3"
  - "rack=1.2.5"
  - "rack=1.3.6"
  - "rack=1.4.1"
  - "rack=master"
  - "tilt=1.2.2"
  - "tilt=1.3.2"
  - "tilt=master"
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-19mode
    - rvm: jruby-19mode
notifications:
  recipients:
    - k.haase@finn.de
